clean: true
sdk: iphonesimulator
xcodebuild_arguments:
 - -project
 - "AAMVABarcodeParser.xcodeproj"
 - -scheme
 - "AAMVABarcodeParser"
 - -sdk
 - iphonesimulator
 - -arch
 - x86_64
author: Applied Recognition, Inc.
module: AAMVABarcodeParser
min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
